version: 2
updates:
  # Configuration des mises à jour des dépendances pour le Backend (server)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
      - "server"
    commit-message:
      prefix: "chore(deps-server)"
      include: "scope"
    versioning-strategy: increase
    groups:
      nestjs-dependencies:
        patterns:
          - "@nestjs/*"
      prisma-dependencies:
        patterns:
          - "@prisma/*"
          - "prisma"
      lint-and-format:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "typescript*"

  # Configuration des mises à jour des dépendances pour le Frontend (client)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
      - "client"
    commit-message:
      prefix: "chore(deps-client)"
      include: "scope"
    versioning-strategy: increase
    groups:
      react-next-dependencies:
        patterns:
          - "react*"
          - "next*"
      tailwind-styling:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
      lint-and-format:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "typescript*"

  # Configuration des actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "ci(actions)"
      include: "scope"